# -*- coding: utf-8 -*-
"""A02_P+x.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcy4dD0WEU7jEGyOmhOTjX4tiP0XFu9s
"""

!pip install -q transformers torch

import re
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
tok = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2").to(device)
model.eval()
print("Loaded GPT-2 on", device, "| vocab size:", len(tok))

TITLE = "The Snow Man\nby Wallace Stevens"

POEM = """One must have a mind of winter
To regard the frost and the boughs
Of the pine-trees crusted with snow;
And have been cold a long time
To behold the junipers shagged with ice,
The spruces rough in the distant glitter
Of the January sun; and not to think
Of any misery in the sound of the wind,
In the sound of a few leaves,
Which is the sound of the land
Full of the same wind
That is blowing in the same bare place
For the listener, who listens in the snow,
And, nothing himself, beholds
Nothing that is not there and the nothing that is."""

lines = POEM.split("\n")
print(len(lines), "lines")

LINE_RE = re.compile(r"^(.*?)([A-Za-z][A-Za-z'\-]*)([^A-Za-z]*)$")

def split_line(line):
    """'Of the pine-trees crusted with snow;' -> ('Of the pine-trees crusted with', 'snow', ';')"""
    prefix, word, punct = LINE_RE.match(line.rstrip()).groups()
    return prefix.rstrip(), word, punct

for line in lines:
    print(split_line(line))

def build_context(lines, done_lines, i, prefix, mode="poem"):
    """
    mode="line"  -> only the current line so far
    mode="poem"  -> the ORIGINAL poem up to this line, plus the current line so far
    mode="chain" -> the ALREADY-CHANGED poem up to this line (the changes build on each other)
    """
    if mode == "line":
        return prefix
    previous = lines[:i] if mode == "poem" else done_lines[:i]
    return TITLE + "\n\n" + "\n".join(previous + [prefix])

# Mark which tokens count as real words: a leading space followed by letters only.
# This skips punctuation, newlines and word pieces like "ing".
vocab = [tok.decode([i]) for i in range(len(tok))]
is_word = torch.tensor([
    s.startswith(" ") and s[1:].isalpha() and s[1:].isascii() for s in vocab
])

def ranked_words(context, n):
    """Return the top-n whole-word guesses as (word, probability), most likely first."""
    ids = tok.encode(context, return_tensors="pt").to(device)
    with torch.no_grad():
        logits = model(ids).logits[0, -1]           # scores for the next token
    probs = torch.softmax(logits, dim=-1)
    ranked = torch.argsort(logits, descending=True).cpu()
    ranked = ranked[is_word[ranked]]               # keep only real words
    return [(vocab[t].strip(), probs[t].item()) for t in ranked[:n].tolist()]

# Test: GPT-2's top 10 guesses for the end of line 1
prefix, word, punct = split_line(lines[0])
for rank, (w, p) in enumerate(ranked_words(prefix, 10), start=1):
    print(f"{rank:>2}. {w:<12} {p:.4f}")

def p_plus_x(lines, x, mode="poem", show=True):
    done = []
    for i, line in enumerate(lines):
        prefix, word, punct = split_line(line)
        context = build_context(lines, done, i, prefix, mode)
        new_word, prob = ranked_words(context, x)[x - 1]   # rank x = position x-1
        new_line = f"{prefix} {new_word}{punct}"
        done.append(new_line)
        if show:
            print(f"{word:>10} -> {new_word:<12} (p={prob:.5f})")
    return "\n".join(done)

p7 = p_plus_x(lines, 7)
print("\n" + p7)

with open("P+7.txt", "w") as f:
    f.write(TITLE + "\n(P+7 version)\n\n" + p7 + "\n")

for x in [34]:
    print(f"\n===== P+{x} =====")
    print(p_plus_x(lines, x, show=False))

X = 34   # <- change this to the x you liked best

px = p_plus_x(lines, X)
print("\n" + px)

filename = f"P+{X}.txt"
with open(filename, "w") as f:
    f.write(TITLE + f"\n(P+{X} version)\n\n" + px + "\n")

from google.colab import files
files.download("P+7.txt")
files.download(filename)

files.download("P+7.txt")
files.download(filename)