# -*- coding: utf-8 -*-
"""generate_images

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMupHSgKU4bwoU88fuRRCY5H1VMhEhT6
"""

!pip install -q diffusers transformers accelerate torch

# CART498 - A1: "Out of Office" - surreal symbolic-pairing collage landscapes using Diffusers
# Inspired by Jan Dziaczkowski's postcard collages, Hannah Hoch and Max Ernst
import torch, os
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("Lykon/dreamshaper-8", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

base = ("collage, surreal 1960s roadside motel postcard, wide landscape view, single-story white motel "
        "small swimming pool on the green lawn, tall rose garden, ")
style = ("Dada surrealist photomontage, cubist fragments, futurist speed lines, torn paper collage,")

prompts = {
    1: base + "a gigantic antique brass pocket watch rising behind the motel roof, " + style,
    2: base + "the swimming pool filled to the brim with floating white paper envelopes and letters "
              ", " + style,
    3: base + "colourful mushrooms growing from the lawn, growing in different directions, " + style,
}
negative = "people, person, face, portrait, blurry, low quality, deformed, text, letters on signs, watermark, modern photograph"

SEED = 1944  # same seed for all three = similar-looking variations
os.makedirs("A1", exist_ok=True)

for n, prompt in prompts.items():
    generator = torch.Generator("cuda").manual_seed(SEED)
    image = pipe(prompt, negative_prompt=negative, num_inference_steps=30,
                 guidance_scale=5.5, width=768, height=512, generator=generator).images[0]
    image.save(f"A1/outofoffice_{n}.jpg", quality=95)
    with open(f"A1/outofoffice_{n}.txt", "w") as f:
        f.write(prompt)
    display(image)

!zip -r A1.zip A1
from google.colab import files
files.download("A1.zip")