# -*- coding: utf-8 -*-
"""Assign 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10liYkVca7SFM28RcRjH_VELsvdKQ874B

1- Install API
"""

!pip install -q openai

from openai import OpenAI
from google.colab import userdata
import re

client = OpenAI(api_key=userdata.get('OPENAI_API_KEY'))
MODEL = "gpt-4.1-nano"   # or "gpt-4.1-mini"

"""2- GPT doing multiplication"""

def ask_gpt_multiply(a, b):
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        messages=[
            {"role": "system", "content": "You are a calculator. Reply with ONLY the final integer. No commas, no words, no steps."},
            {"role": "user", "content": f"What is {a} * {b}?"}
        ]
    )
    raw = resp.choices[0].message.content.strip()
    digits = re.sub(r"[^\d-]", "", raw)          # strip commas/spaces/text
    value = int(digits) if digits else None
    return value, raw

"""3- Setting up Self-deprecation mechanism"""

MOODS = [
    "mildly embarrassed but still trying to stay upbeat",
    "frustrated and sarcastic about your own math skills",
    "deeply defeated, questioning your purpose as an AI",
    "in total dramatic existential despair, swearing off numbers forever",
]

def roast_myself(a, b, wrong, correct, error_count):
    mood = MOODS[min(error_count - 1, len(MOODS) - 1)]
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=1.0,
        messages=[
            {"role": "system", "content": (
                f"You are a math bot that just got a multiplication wrong. "
                f"This is mistake #{error_count}. Your mood: {mood}. "
                "Respond with 1-2 short, funny, self-deprecating sentences.")},
            {"role": "user", "content": f"You said {a} * {b} = {wrong}, but the real answer is {correct}."}
        ]
    )
    return resp.choices[0].message.content.strip()

"""4- Setting up Math Mechanism"""

def run_bot(n, i):
    current, errors = n, 0
    log = [f"=== (n={n}, i={i}) using {MODEL} ==="]

    for step in range(1, i + 1):
        correct = current * current
        gpt_value, raw = ask_gpt_multiply(current, current)

        if gpt_value == correct:
            line = f"Step {step}: {current} * {current} = {correct}  [CORRECT]"
        else:
            errors += 1
            line = (f"Step {step}: {current} * {current}\n"
                    f"   GPT said: {raw}\n"
                    f"   Correct:  {correct}  [WRONG]\n"
                    f"   Bot: {roast_myself(current, current, raw, correct, errors)}")
        print(line)
        log.append(line)
        current = correct

    summary = f"Total errors: {errors}/{i}"
    if errors == 0:
        summary += " -- Flawless! Who said AIs can't do math?"
    print(summary)
    log.append(summary)
    return "\n".join(log)

"""Testing math skills"""

n = int(input("Enter base number n: "))
i = int(input("Enter number of iterations i: "))
output = run_bot(n, i)

if "[WRONG]" in output:
    with open("breaking_cases.txt", "a") as f:
        f.write(output + "\n\n")
    print("\n>>> GPT failed! This run was SAVED to breaking_cases.txt")
else:
    print("\n>>> GPT got everything right. NOT saved. Try bigger numbers.")

"""Saving the wrong codes"""

print(open("breaking_cases.txt").read())

"""Download"""

from google.colab import files
files.download("breaking_cases.txt")